### PR TITLE
chore: rm govulncheck

### PR DESCRIPTION
**Pull request by sashamelentyev**

### CODE REVIEW

**Comment by ccoVeille** [comment]
May we have some context about this removal?

Was it useless? Were there problems with having it?

Thanks

**Comment by ccoVeille** [comment]
I'm asking because I started considering adding it to some repository I know

**Comment by sashamelentyev** [comment]
In usestdlibvars govulncheck is useless, because usestdlibvars is just static analyzer. I haven't some problems with  govulncheck - good thing

**Comment by ccoVeille** [comment]
Thanks for confirming what my thoughts

**Pull request merged**
