### PR TITLE
feat: add linter options

### PR DESCRIPTION
**Pull request by sashamelentyev**

### CODE REVIEW

**Comment by sashamelentyev** [comment]
@ldez, please, review this. I added options concept

**Comment by ldez** [comment]
I think we did not understand each other about what I meant by option.

I was thinking about something like that:
```
time-weekday: true
time-month: true
...
```

**Comment by sashamelentyev** [comment]
@ldez added exclude options

**Comment by ldez** [comment]
https://github.com/sashamelentyev/usestdlibvars/compare/main...ldez:usestdlibvars:feat/options

**Comment by sashamelentyev** [comment]
Perfect! I close this PR

**Pull request closed without merging**
